a = input('Element? ')
b = input('Element? ')
c = input('Element? ')
d = input('Element? ')
e = input('Element? ')
f = input('Element? ')
list = []
list.append(a)
list.append(c)
list.append(e)
list.append(b)
list.append(d)
list.append(f)
print(list)